name: 'Run the thing'

on: push

jobs:
  Run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100'
        
    - run: |
        powershell gen.ps1
